### ISSUE TITLE
How to get dominating frequency of the signal

### ISSUE THREAD

**Issue by cygerts** [jakevdp/nfft#11]
So my question is how can we get dominating frequency / frequencies from the signal?

That is sth I can achieve with scipy.FFTPACK using code like that:
import scipy.fftpack as syfp
 X = syfp.fft(signal)
 freqs = syfp.fftfreq(len(signal)) * SamplesPerSecond
dominatingFreqId= np.argsort(np.abs(X))[-1]
freq = freqs[dominatingFreqId]

How can I achieve that with NFFT, but of course on not equally spaced samples? I.e. it would be nice if I can  get the frequency using code sample by jakevdp from this thread: https://github.com/jakevdp/nfft/issues/7

**Comment by jakevdp** [comment]
You should look into the Lomb-Scargle Periodogram.

**Comment by jakevdp** [comment]
http://docs.astropy.org/en/stable/stats/lombscargle.html

**Comment by cygerts** [comment]
Great, many thx.
Just wondering, do you have any recommendation what should I use when the signal is evently spaced? Maybe what I am using (scipy.fftpack) is not optimal in that case?

**Comment by jakevdp** [comment]
For evenly-spaced signals, a PSD computed with the FFT is the best approach. It's mathematically provable that you cannot do better.

**Comment by cygerts** [comment]
Great, many thanks
