### ISSUE TITLE
What is the complexity of your implementation

### ISSUE THREAD

**Issue by certik** [jakevdp/nfft#3]
Very nice package! I was wondering what the complexity is if your particular implementation. The 1D FFT is O(N*log(N)), I assume your algorithm depends on N, M and the accuracy eps. You can put this information in the README, I think it would be very useful to readers.

**Comment by jakevdp** [comment]
Great idea – I just added this to the README.

**Comment by certik** [comment]
Thanks @jakevdp for clarifying it.
