### ISSUE TITLE
Problem with installation with conda

### ISSUE THREAD

**Issue by stormyweathers** [jakevdp/nfft#9]
Hey there,

I installed this module with conda.  The output from "conda list" shows:
nfft                      3.2.4             hf8c457e_1000    conda-forge

but when I try to use the module I get:

>>> import nfft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nfft'

**Comment by jakevdp** [comment]
Make sure your Python environment matches the environment where you installed the package.

**Comment by stormyweathers** [comment]
thanks for the quick response!

I installed it and attempted to access it in my base environment

**Comment by stormyweathers** [comment]
Originally, I had nfft provided by pynfft.  I tried uninstalling pynfft and then updating nfft to version 3.4.1, but I still have the same problem.

I was able to import pynfft, however.

**Comment by stormyweathers** [comment]
oops! It turns out that conda installed the c-library nfft, and is not aware of your pure python nfft package.

When I installed with pip, everything works fine.
